#### Data Diri

**Nama:** Bayu Setiawan

**NIM:** 026

In [51]:
import tensorflow as tf
import numpy as np
from prettytable import PrettyTable

print(tf.__version__)

2.10.0


#### 1. Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.

In [29]:
random_tensor = tf.random.uniform(shape=(5, 5), minval=1, maxval=40, dtype=tf.int32)

random_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[17,  6, 14, 39,  2],
       [33, 31, 36, 25, 38],
       [17,  2,  1,  2, 18],
       [13, 28, 29, 13,  2],
       [18, 17, 35, 17, 23]])>

#### 2. Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

In [4]:
prime_tensor = tf.convert_to_tensor([[2, 3, 5, 7, 11], [17, 19, 23, 29, 31], [37, 41, 43, 47, 53], [59, 61, 67, 71, 73], [79, 83, 89, 97, 101]])

prime_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  2,   3,   5,   7,  11],
       [ 17,  19,  23,  29,  31],
       [ 37,  41,  43,  47,  53],
       [ 59,  61,  67,  71,  73],
       [ 79,  83,  89,  97, 101]])>

#### 3. Tampilkan dimensi dari kedua variable tersebut.

In [6]:
table = PrettyTable(["Variable", "Dimensi"])
table.align = "l"

table.add_row(["random_tensor", random_tensor.shape])
table.add_row(["prime_tensor", prime_tensor.shape])

print(table)

+---------------+---------+
| Variable      | Dimensi |
+---------------+---------+
| random_tensor | (5, 5)  |
| prime_tensor  | (5, 5)  |
+---------------+---------+


#### 4. Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).

In [46]:
res_add = tf.add(random_tensor, prime_tensor)
res_subtract = tf.subtract(random_tensor, prime_tensor)
res_divide = tf.divide(random_tensor, prime_tensor)
res_multiply = tf.multiply(random_tensor, prime_tensor)
res_pow = tf.pow(random_tensor, prime_tensor)

table = PrettyTable(["Operator", "Hasil"])
table.title = "Aritmetika"
table.align = "l"

table.add_row(["add", tf.keras.backend.get_value(res_add)])
table.add_row(["subtract", tf.keras.backend.get_value(res_subtract)])
table.add_row(["divide", tf.keras.backend.get_value(res_divide)])
table.add_row(["multiply", tf.keras.backend.get_value(res_multiply)])
table.add_row(["pow", tf.keras.backend.get_value(res_pow)])

print(table)

+----------------------------------------------------------------------------+
|                                 Aritmetika                                 |
+----------+-----------------------------------------------------------------+
| Operator | Hasil                                                           |
+----------+-----------------------------------------------------------------+
| add      | [[ 19   9  19  46  13]                                          |
|          |  [ 50  50  59  54  69]                                          |
|          |  [ 54  43  44  49  71]                                          |
|          |  [ 72  89  96  84  75]                                          |
|          |  [ 97 100 124 114 124]]                                         |
| subtract | [[ 15   3   9  32  -9]                                          |
|          |  [ 16  12  13  -4   7]                                          |
|          |  [-20 -39 -42 -45 -35]                 

#### 5. Tampilkan nilai maksimum dan minimum dari variable random_tensor.

In [64]:
row_maxs = tf.argmax(random_tensor, axis = 1)
row_mins = tf.argmin(random_tensor, axis = 1)
maxs = []
mins = []

for index, max_idx in enumerate(row_maxs):
    maxs.append(random_tensor[index][max_idx].numpy())

for index, min_idx in enumerate(row_mins):
    mins.append(random_tensor[index][min_idx].numpy())

print(f"Nilai Maksimal: {max(maxs)}")
print(f"Nilai Maksimal: {min(mins)}")

Nilai Maksimal: 39
Nilai Maksimal: 1


#### 6. Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [68]:
concat_tensor = tf.concat([random_tensor, prime_tensor], axis=1)

concat_tensor

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[ 17,   6,  14,  39,   2,   2,   3,   5,   7,  11],
       [ 33,  31,  36,  25,  38,  17,  19,  23,  29,  31],
       [ 17,   2,   1,   2,  18,  37,  41,  43,  47,  53],
       [ 13,  28,  29,  13,   2,  59,  61,  67,  71,  73],
       [ 18,  17,  35,  17,  23,  79,  83,  89,  97, 101]])>

#### 7. Tampilkan hasil sorting dari kedua variable di atas (descending)

In [71]:
random_asc = tf.sort(random_tensor, direction="ASCENDING")
random_desc = tf.sort(random_tensor, direction="DESCENDING")
prime_asc = tf.sort(prime_tensor, direction="ASCENDING")
prime_desc = tf.sort(prime_tensor, direction="DESCENDING")


table = PrettyTable(["Variable", "Metode", "Hasil"])
table.title = "Sorting"
table.align = "l"

table.add_row(["random", "asc", tf.keras.backend.get_value(random_asc)])
table.add_row(["random", "desc", tf.keras.backend.get_value(random_desc)])
table.add_row(["prime", "asc", tf.keras.backend.get_value(prime_asc)])
table.add_row(["prime", "desc", tf.keras.backend.get_value(prime_desc)])
print(table)

+---------------------------------------------+
|                   Sorting                   |
+----------+--------+-------------------------+
| Variable | Metode | Hasil                   |
+----------+--------+-------------------------+
| random   | asc    | [[ 2  6 14 17 39]       |
|          |        |  [25 31 33 36 38]       |
|          |        |  [ 1  2  2 17 18]       |
|          |        |  [ 2 13 13 28 29]       |
|          |        |  [17 17 18 23 35]]      |
| random   | desc   | [[39 17 14  6  2]       |
|          |        |  [38 36 33 31 25]       |
|          |        |  [18 17  2  2  1]       |
|          |        |  [29 28 13 13  2]       |
|          |        |  [35 23 18 17 17]]      |
| prime    | asc    | [[  2   3   5   7  11]  |
|          |        |  [ 17  19  23  29  31]  |
|          |        |  [ 37  41  43  47  53]  |
|          |        |  [ 59  61  67  71  73]  |
|          |        |  [ 79  83  89  97 101]] |
| prime    | desc   | [[ 11   7   5   3 